AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "Guardfile"
    - "config/deploy.rb"
    - "config/deploy/**/*"
    - "config/unicorn/*"
    - "config/initializers/**/*"
    - "lib/memsize.rb"
  DisplayCopNames: true
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/BlockLength:
  CountComments: false
  Max: 50
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/initializers/*.rb'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 3

Style/FrozenStringLiteralComment:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%":  "!!"
    "%i": "[]"
    "%q": "!!"
    "%Q": "!!"
    "%r": "!!"
    "%s": "()"
    "%w": "[]"
    "%W": "[]"
    "%x": "()"

Style/StringLiterals:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ClassVars:
  Enabled: true

Style/WordArray:
  MinSize: 3

Style/SymbolArray:
  MinSize: 3

Metrics/PerceivedComplexity:
  Max: 11

Style/IfUnlessModifier:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/Semicolon:
  Exclude:
    - "spec/**/*"

Style/FormatString:
  EnforcedStyle: percent

Style/NumericLiterals:
  MinDigits: 7

Style/PredicateName:
  NamePrefixBlacklist:
    - "is_"
    - "have_"
  NamePrefix:
    - "is_"
    - "have_"

Layout/IndentHash:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: true

Style/LineEndConcatenation:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/Not:
  Enabled: true

Style/RedundantSelf:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false
